### ISSUE TITLE
Correção do Pong

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/pong.fabsoftware.itp.ifsp.edu.br#2]
Atualmente o jogo é dividido em duas partes, tela e controle. Fazer com que a tela e o controle estejam no cliente para jogar.
- Trazer a tela para o cliente
- Esperar o outro jogador para poder entrar.
- Avisar caso o jogador saia da jogo

**Comment by rafalmeida-ifsp** [comment]
Fechado (deprecated).
