### ISSUE TITLE
Melhorias Pong 2.0

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/pong.fabsoftware.itp.ifsp.edu.br#7]
- Transformar para PCs
- Arrumar problema de sincronização das telas em diferentes PCs
- Implementação da salas

**Comment by danilocbueno** [comment]
- Arrumar a velocidade do pong
- Padronizar para telas inicias e finais
- Verificar como fazer animações dentro do canvas (igual do video do space no discord)

**Comment by rafalmeida-ifsp** [comment]
- [x] - Arrumar a velocidade do pong
- [x] - Padronizar para telas inicias e finais
- [x] - Deixar só uma sala
- [x] - Testar
